# **Trabalho HoG (Histogram of Gradients) - Ciência da Computação - Daiane Babicz**

**Instalação de dependências**

In [11]:
from google.colab import drive
drive.mount('/content/gdrive')

from skimage import feature
from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import train_test_split
import numpy as np
import os
import cv2

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


**Implementando a função que extrai os descritores HoG:**

In [12]:
def get_hog_features(img):
    # Redimensione a imagem para 64x128 pixels (padrão do HoG Descriptor)
    img = cv2.resize(img, (64, 128))

    # Calcula os recursos HoG
    hog_features = feature.hog(img, orientations=9, pixels_per_cell=(8, 8),
                               cells_per_block=(2, 2), block_norm='L2-Hys')

    return hog_features

**Carregar as imagens e extrair os descritores HoG:**

In [22]:
def load_images_from_folder(folder):
    images = []
    labels = []
    for label, subfolder in enumerate(os.listdir(folder)):
        for filename in os.listdir(os.path.join(folder, subfolder)):
            img = cv2.imread(os.path.join(folder, subfolder, filename), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                hog_features = get_hog_features(img)
                images.append(hog_features)
                labels.append(label)
                if len(images) <= 5:  # apenas para os primeiros 5 vetores de características
                    print(hog_features)
    return images, labels

images, labels = load_images_from_folder('/content/gdrive/MyDrive/Visão Computacional/Trabalho HoG/fruits-dataset')


[0.26234651 0.26234651 0.00932757 ... 0.02699238 0.03849897 0.13447026]
[0.2208121  0.0469735  0.0079333  ... 0.04771054 0.05449771 0.28605453]
[0.05523612 0.01719664 0.06132645 ... 0.12411643 0.16630505 0.03886744]
[0.11506369 0.05559705 0.         ... 0.         0.         0.        ]
[0.31372462 0.02198031 0.00718005 ... 0.16731172 0.26625062 0.06549126]


**Dividindo o conjunto de dados em treino e teste:**

In [17]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.3, random_state=400)

**Treinar o classificador SVM:**

In [18]:
clf = svm.SVC()
clf.fit(X_train, y_train)

SVC()

**Testar o modelo e extrair as métricas:**

In [19]:
y_pred = clf.predict(X_test)

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred, average='micro'))

Accuracy: 0.5607893061744113
Precision: 0.5607893061744113
